package com.laigu.laigu.card;

import java.util.List;

/**
 * 卡牌目录。本文件由 tools/generate_cards.py 自动生成，勿手改。
 * 每个 id 对应一套「普通 + 金质」两张卡（<id>_common / <id>_gold）。
 */
public final class CardCatalog {
    public static final List<String> CARD_IDS = List.of(
            "t_xing_bo_hua",
            "wan_he_song_feng_tu",
            "wan_gong_jiao",
            "san_tu_zao_jing",
            "shang_yang_tai_tie",
            "yun_lei_wen_da_nao",
            "wu_xian_pi_pa",
            "wu_xing_chu_dong_fang",
            "ya_chang_niu_zun",
            "tu_xing_tao_xun",
            "li_gui",
            "shi_er_hua_hui_bei",
            "qian_li_jiang_shan",
            "wu_men",
            "juan_yun_jin_la_ba",
            "xiang_ri_kui",
            "shang_zhou_shi_gong",
            "si_long_si_feng_zuo",
            "wai_xiao_bi_zhi",
            "tian_wang_shi_ke",
            "tian_qiu_yi",
            "tai_yang_shen_niao",
            "song_jin_xiang_shi",
            "xiao_song_xiang_lu",
            "guang_cai_miao_jin_hu",
            "pang_bei",
            "cai_feng_ming_qi",
            "wei_suo_jia_ju",
            "yuan_wang_bei",
            "dun_huang_fei_tian",
            "duan_bi_wei_na_si",
            "xing_yue_ye",
            "jin_hou_niao_zun",
            "zeng_hou_yi_bian_zhong",
            "tao_yuan_xian_jing_tu",
            "mao_gong_ding",
            "shui_jing_bei",
            "han_mo_la_bi_fa_dian",
            "luo_shen_fu_tu",
            "hun_tian_yi",
            "hai_shui_jiang_ya_lu",
            "hai_cuo_tu",
            "xi_shan_xing_lv_tu",
            "li_mao_pan",
            "wang_shi_shu_han_juan",
            "bai_shi_san_le",
            "bai_hua_tu_juan",
            "zhen_zhu_bao_chuang",
            "shui_lian",
            "qiu_cao_bei",
            "qin_gong_bo",
            "su_sha_dan_yi",
            "fu_rong_lu",
            "mo_gao_ku_220",
            "mo_gao_ku_ji",
            "lian_tang_ru_ya_tu",
            "fu_tao_ping",
            "jia_hu_gu_di",
            "chi_bi_fu_ye",
            "yue_wang_gou_jian_jian",
            "jiu_zhang",
            "jin_guan_dai",
            "jin_ou_yong_gu_bei",
            "jin_shi_lu",
            "jin_chan_yu_ye",
            "liu_jin_qi_shi",
            "tong_zuo_long",
            "tong_hu_di_lou",
            "tong_ben_ma",
            "tong_che_ma",
            "yin_que_shan_han_jian_1",
            "yin_que_shan_han_jian_2",
            "yin_xiang_nang",
            "xue_jing_han_lin_tu",
            "qing_ci_lian_hua_zun",
            "qing_tong_xian_he",
            "niao_yin_shan_shui_zhong",
            "lu_wang_ben_sheng_tu",
            "lin_zhi_ma_ti_jin"
    );

    private CardCatalog() {}
}
